# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            وحید معصومی
tagline:          'Vahid Masoumi'
description:      'از تجربیات شخصیم درباره چیزهای جالب و به خصوص حوزه دیتا می‌نویسم'
avatar: 'https://avatars3.githubusercontent.com/u/6222662?s=460&v=4'
url:              https://databazi.ir/

author:
  name:           'وحید معصومی'
  url:            https://databazi.ir/


paginate:         2
google_analytics: 'UA-136938072-1'
emailme:          mailto:vhdmsm@gmail.com

gems:             [jekyll-paginate, jekyll-seo-tag, jekyll-sitemap]

github:
  repo:           https://github.com/vhdmsm/vhdmsm.github.io

tags: machine-learning

disqus: vhdmsm-github-io
email: vhdmsm@gmail.com
github: vhdmsm
instagram: vhdmsm
linkedin: vhdmsm
twitter: vhdmsm

